### ISSUE TITLE
watermelon_id generation

### ISSUE THREAD

**Issue by LucasESchuster** [nathanheffley/laravel-watermelon#13]
Hi, I would like to know how to create a record using a non-mobile application. For example, my user creates a record in the web system, how will it be possible to create this record, knowing that watermelon_id is a mandatory field?

**Comment by nathanheffley** [comment]
I see you've already marked this as closed, I assume you realized you can just fill the field yourself? As long as it's unique among all Watermelon objects it'll work fine. Using a large UUID generator will suffice without having to check for existing values.
