### ISSUE TITLE
Compatibility with Laravel 10

### ISSUE THREAD

**Issue by leoboom-isme** [nathanheffley/laravel-watermelon#4]
Hello guys.

It seems this package is not able to be installed on Laravel 10 with PHP 8.2. Will you be updating it for Laravel 10?

![image](https://github.com/nathanheffley/laravel-watermelon/assets/103731876/47b5ba98-839c-488b-a690-d6663bdbf9b3)

Many thanks!

**Comment by nathanheffley** [comment]
Hey! I would guess that this is a simple fix and the composer.json file just needs to be updated to allow for newer versions of Laravel. I will get to it at some point, if you know how, a PR to update it would make this happen a lot faster.

Thanks for letting me know!

**Comment by nathanheffley** [comment]
v0.0.3 should resolve this issue for you @leoboom-isme
