### ISSUE TITLE
Laravel accessors and mutators  does not work as expected when eloquent model is syncable 

### ISSUE THREAD

**Issue by ahsan85** [nathanheffley/laravel-watermelon#9]
Currently, I've encountered an issue where the use of accessors and mutators during record synchronization modifies records, leading to unexpected bugs. Is there any way to  to leverage these functionalities (accessors and mutators ) for web actions (modify model from website ) not for syncing.

Model : 
```  
class TimeRecord extends Model
{
    use SoftDeletes, HasUuids, Watermelon;

    protected $guarded = [];

    protected array $watermelonAttributes = [
        'time_record_guid',
        'employee_guid',
        'employee_name_last_name_first',
        'work_date',
    ];

    protected function workDate(): Attribute
    {
        return Attribute::make(
            get: fn($value) => formatDateUserTz($value, 'm/d/Y'),
            set: fn($value) => strtotime($value)
        );
    }

}


```
Controller : 

```  
  public function update(Request $request, TimeRecord $timeRecord)
    {

        $timeRecord->work_date = strtotime($request->work_date);

        $timeRecord->save();
    }
```

**Comment by nathanheffley** [comment]
I'm not sure what kind of error you are referring to. The `Watermelon` trait doesn't hook into the regular lifecycle of the model, if you modify a record with your own custom code like in the controller shown the Watermelon trait shouldn't have anything to do with that nor should it interfere. If you can explain in more detail what kind of issues you are having (or ideally, create a brand new Laravel Sail project, require just this package, and then replicate the issue with some steps I can follow) I would be glad to look into this for you.

**Comment by nathanheffley** [comment]
I am still not sure what is going on with this issue, please file another one with a reproduction and I'd be more than happy to look into it.
